openapi: 3.0.3
info:
  termsOfService: https://termofservice.it
  title: 'Stato della piattaforma PN'
  x-summary: 'Stato della piattaforma PN'
  version: '1.0.0'
  description: >- 
    Queste API permettono:<br/>
    - la visualizzazione dello stato dei servizi di Piattaforma Notifiche 
    e dello storico dei disservizi; per ogni disservizio è possibile scaricare il corrispondente
    atto opponibile a terzi corrispondente. <br/>
    - l'inserimento di eventi di inizio o fine di un disservizio utile in quei casi in cui il 
    sistema automatico non rivela il problema. <br/>
    __N.B.:__ gli atti opponibili a terzi vengono generati solo per i disservizi conclusi.
  contact:
    email: pn@pagopa.it
  license:
    name: Licenza di PN
    url: 'https://da-definire/'
servers:
- url: https://api.pn.pagopa.it
  description: Ambiente di produzione
- url: https://api.uat.pn.pagopa.it
  description: Ambiente di test
- url: https://api.dev.pn.pagopa.it
  description: Ambiente di sviluppo
tags:
  - name: HealthCheck
    description: >-
      Invocazioni per sapere lo stato di PN
  - name: Read
    description: >-
      Lettura dello stato di PN, API pubbliche
  - name: Write
    description: >-
      Aggiornamento dello stato di PN, API sottoposte ad autenticazione.

paths:
    ##########################################################################################
    ###                           API DI STATO RICHIESTE DA AGID                           ###
    ##########################################################################################
  
  "/healthcheck":
    get:
      summary: healthCheck path
      description: health check path per verificare lo stato del micro servizio
      tags:
        - HealthCheck
      operationId: healthcheck
      responses:
        '200':
          description: Ok
        '500':
          description: Internal Server Error  
    ###########################################################################################
    ###                                 LETTURA DELLO STATO                                 ###
    ###########################################################################################
  "/status":                                                                                            # ONLY EXTERNAL
    get:                                                                                                # ONLY EXTERNAL
      summary: status path                                                                         # ONLY EXTERNAL
      description: >-                                                                                   # ONLY EXTERNAL
        Questo path e questo metodo devono, per richiesta di AGID, restituire <br/>                     
          - status 200 se la piattaforma notifica è correttamente funzionante, <br/>                    
          - status 500 se la piattaforma ha un funzionamento degradato. <br/>                           
        Il body e lasciato libero quindi utilizziamo quanto già definito per il path                    
        /downtime/status                                                                                
      tags:                                                                                             # ONLY EXTERNAL  
        - Read                                                                                          # ONLY EXTERNAL
  #    security:                                                                                         # ONLY EXTERNAL
  #      - bearerAuth: [ ]                                                                               # ONLY EXTERNAL
      operationId: status                                                                               # ONLY EXTERNAL
      x-api-permissions:                                                                                
        - 'api-key-read'                                                                                
        - 'log-downtime-read'                                                                           
      responses:                                                                                        # ONLY EXTERNAL  
        '200':                                                                                          # ONLY EXTERNAL
          description: Ok                                                                               # ONLY EXTERNAL
          content:                                                                                      # ONLY EXTERNAL
            application/problem+json:                                                                   # ONLY EXTERNAL
              schema:                                                                                   # ONLY EXTERNAL
                $ref: "./schemas-pn-components-v1.yaml#/components/schemas/PnStatusResponse"            # ONLY EXTERNAL
              example:                                                                                  # ONLY EXTERNAL
                functionalities: [NOTIFICATION_CREATE,NOTIFICATION_VISUALIZATION,NOTIFICATION_WORKFLOW] # ONLY EXTERNAL
                openIncidents: []                                                                       # ONLY EXTERNAL
        '500':                                                                                          # ONLY EXTERNAL  
          description: Internal Server Error                                                            # ONLY EXTERNAL
          content:                                                                                      # ONLY EXTERNAL
            application/problem+json:                                                                   # ONLY EXTERNAL
              schema:                                                                                   # ONLY EXTERNAL
                $ref: "./schemas-pn-components-v1.yaml#/components/schemas/PnStatusResponse"            # ONLY EXTERNAL
              example:                                                                                  # ONLY EXTERNAL
                functionalities: [NOTIFICATION_CREATE,NOTIFICATION_VISUALIZATION,NOTIFICATION_WORKFLOW] # ONLY EXTERNAL
                openIncidents:                                                                          # ONLY EXTERNAL
                  - functionality: NOTIFICATION_CREATE                                                  # ONLY EXTERNAL
                    status: KO                                                                          # ONLY EXTERNAL
                    startDate: "2019-08-24T14:15:22Z"                                                   # ONLY EXTERNAL
        '400':                                                                                          # ONLY EXTERNAL
          description: Bad request                                                                      # ONLY EXTERNAL
          content:                                                                                      # ONLY EXTERNAL    
            application/problem+json:                                                                   # ONLY EXTERNAL
              schema:                                                                                   # ONLY EXTERNAL
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'                         # ONLY EXTERNAL
  "/downtime/v1/status":
    get:
      summary: Stato attuale
      description: >-
        Metodo che restituisce l'elenco delle funzionalità di Piattaforma Notifiche e l'elenco
        dei disservizi presenti al momento dell'invocazione.
      tags:
        - Read
      security:                                                                                         # ONLY EXTERNAL
        - bearerAuth: [ ]                                                                               # ONLY EXTERNAL
      operationId: currentStatus
      x-api-permissions:
        - 'api-key-read'
        - 'log-downtime-read'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: "./schemas-pn-components-v1.yaml#/components/schemas/PnStatusResponse"
              example:
                - functionalities: [NOTIFICATION_CREATE,NOTIFICATION_VISUALIZATION,NOTIFICATION_WORKFLOW]
                  openIncidents:
                    - functionality: NOTIFICATION_CREATE
                      status: KO
                      startDate: "2019-08-24T14:15:22Z"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'

  "/downtime/v1/history":
    get:
      summary: Ricerca storico disservizi
      description: >-
        Elenco dei disservizi di Piattafoma Notifiche riscontrate nel lasso di tempo specificato 
        dai parametri _fromTime_ e _toTime_. <br/>
        Il parametro _functionality_ è opzionale e ripetibile; permette di filtrare i disservizi 
        estratti limitandoli a quelli impattanti le funzionalità elencate.
      tags:
        - Read
 #     security:                                                                                         # ONLY EXTERNAL
 #       - bearerAuth: [ ]                                                                               # ONLY EXTERNAL
      operationId: statusHistory
      x-api-permissions:                                                                                
        - 'api-key-read'                                                                                
        - 'log-downtime-read'                                                                          
      parameters:
        - $ref: '#/components/parameters/queryFromTime'
        - $ref: '#/components/parameters/queryToTime'
        - $ref: '#/components/parameters/queryFunctionality'
        - $ref: '#/components/parameters/queryPage'
        - $ref: '#/components/parameters/querySize'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                  $ref: "./schemas-pn-components-v1.yaml#/components/schemas/PnDowntimeHistoryResponse"
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'


    ###########################################################################################
    ###                          DOWNLOAD ATTI OPPONIBILI A TERZI                           ###
    ###########################################################################################

  "/downtime/v1/legal-facts/{legalFactId}":
    get:
      summary: Ottieni atto opponibile a terzi
      description: >-
        Fornisce le informazioni per scaricare un atto opponibile a terzi o, se tale atto va 
        recuperato dagli archivi, fornisce una stima per eccesso di quanti secondi bisogna 
        attendere.
      tags:
        - Read
  #    security:                                                                                         # ONLY EXTERNAL
  #      - bearerAuth: [ ]                                                                               # ONLY EXTERNAL
      operationId: getLegalFact
      x-api-permissions:                                                                                
        - 'api-key-read'                                                                                
        - 'log-downtime-read'                                                                           
      parameters:
        - name: legalFactId
          in: path
          required: true
          description: Identificativo dell'atto opponibile a terzi che si vuole scaricare
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:  
            application/json:
              schema:
                $ref: "./schemas-pn-components-v1.yaml#/components/schemas/LegalFactDownloadMetadataResponse"
              examples:
                hot:
                  summary: File disponibile
                  value:
                    filename: downtime_NEW_NOTIFICATION_20221204.pdf
                    contentLength: 32423
                    url: "https://s3............com/presigned-url"
                cold:
                  summary: File archiviato
                  value:
                    filename: downtime_NEW_NOTIFICATION_20221204.pdf
                    contentLength: 32423
                    retryAfter: 7200    
        '204':
          description: Not signed
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'
        '404':
          description: Not found
          content:
            application/problem+json:
              schema:
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'


    ###########################################################################################
    ###                                MODIFICA DELLO STATO                                 ###
    ###########################################################################################
  "/downtime-internal/v1/events":
    post:
      summary: Modifica stato di servizio
      description: >-
        Permette di aggiungere un evento di inizio o fine di un disservizio, può essere 
        richiamato sia dagli allarmi automatici che da GUI. Tali casi vanno discriminati 
        con l'attributo di richiesta _sourceType_.
      tags:
        - Write
  #    security:                                                                                         # ONLY EXTERNAL
  #      - bearerAuth: [ ]                                                                               # ONLY EXTERNAL
      operationId: addStatusChangeEvent
      x-api-permissions:                                                                                
        - 'api-key-write'                                                                                
        - 'log-downtime-write'                                                                           
      parameters:
        - $ref: 'remote-refs.yaml#/components/parameters/uidAuthFleet'
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "./schemas-pn-components-v1.yaml#/components/schemas/PnStatusUpdateEvent"
        required: true
      responses:
        '204':
          description: OK
        '400':
          description: Bad request
          content:
            application/problem+json:
              schema:
                $ref: './schemas-pn-errors-v1.yaml#/components/schemas/Problem'

components:
  parameters:
    
    ###########################################################################################
    ###                          PARAMETRI DI RICERCA DEI DOWNTIME                          ###
    ###########################################################################################
    
    queryFromTime:
      name: fromTime
      in: query
      required: true
      description: data/ora di inizio dell'intervallo entro cui eseguire la ricerca
      schema:
        type: string
        format: date-time
    
    queryToTime:
      name: toTime
      in: query
      required: false
      description: data/ora di fine dell'intervallo entro cui eseguire la ricerca
      schema:
        type: string
        format: date-time
    
    queryFunctionality:
      name: functionality
      in: query
      required: false
      description: funzionalità di Piattaforma Notifiche di cui elencare i disservizi
      schema:
        type: array
        items:
          $ref: './schemas-pn-components-v1.yaml#/components/schemas/PnFunctionality'
    
    queryPage:
      name: page
      in: query
      required: false
      description: Pagina di risultati a cui il client è interessato
      schema:
        type: string
        
    querySize:
      name: size
      in: query
      required: false
      description: Size della pagina di risultati a cui il client è interessato
      schema:
        type: string
  securitySchemes:           # ONLY EXTERNAL                           
    bearerAuth:              # ONLY EXTERNAL                           
      type: http             # ONLY EXTERNAL                           
      scheme: Bearer         # ONLY EXTERNAL                         
      description: JWT       # ONLY EXTERNAL                         
security:                    # ONLY EXTERNAL                         
 - bearerAuth: []            # ONLY EXTERNAL                         
    
